export const AUTH_ERROR_CODE = {
  EMPTY_REFRESH_TOKEN: "EMPTY_REFRESH_TOKEN",
  EMPTY_REGISTER_TOKEN: "EMPTY_REGISTER_TOKEN",
  INVALID_AUTH_CODE: "INVALID_AUTH_CODE",
  INVALID_ID_TOKEN: "INVALID_ID_TOKEN",
  INVALID_REFRESH_TOKEN: "INVALID_REFRESH_TOKEN",
  INVALID_REGISTER_TOKEN: "INVALID_REGISTER_TOKEN",
  INVALID_STATE: "INVALID_STATE",
  LOGIN_FAILED: "LOGIN_FAILED",
  PROVIDER_MISMATCH: "PROVIDER_MISMATCH",
  REFRESH_TOKEN_EXPIRED: "REFRESH_TOKEN_EXPIRED",
  REFRESH_TOKEN_REUSED: "REFRESH_TOKEN_REUSED",
  REGISTER_TOKEN_EXPIRED: "REGISTER_TOKEN_EXPIRED",
  SOCIAL_SERVER_ERROR: "SOCIAL_SERVER_ERROR",
  STATE_EXPIRED: "STATE_EXPIRED",
  STATE_REUSED: "STATE_REUSED",
  UNKNOWN_AUTH_STATUS: "UNKNOWN_AUTH_STATUS",
  UNSUPPORTED_PROVIDER: "UNSUPPORTED_PROVIDER",
} as const;

export type AuthErrorCode = (typeof AUTH_ERROR_CODE)[keyof typeof AUTH_ERROR_CODE];

export const REFRESH_TOKEN_ERROR_CODES = new Set<string>([
  AUTH_ERROR_CODE.EMPTY_REFRESH_TOKEN,
  AUTH_ERROR_CODE.REFRESH_TOKEN_EXPIRED,
  AUTH_ERROR_CODE.INVALID_REFRESH_TOKEN,
  AUTH_ERROR_CODE.REFRESH_TOKEN_REUSED,
]);

export const REGISTER_TOKEN_ERROR_CODES = new Set<string>([
  AUTH_ERROR_CODE.EMPTY_REGISTER_TOKEN,
  AUTH_ERROR_CODE.REGISTER_TOKEN_EXPIRED,
  AUTH_ERROR_CODE.INVALID_REGISTER_TOKEN,
]);
